# optim
defaults:
  - override hydra/launcher: joblib
seed: 3407
in_size: 16
out_size: 8
epochs: 3
optim: 'adam'
lr: 5e-4
wd: 1e-1
bs: 32
power: 1
dim1: 22
ite: 130
path: './checkpoint/BCIcha/'
hydra:
  run:
    dir: outputs/BCIcha/
  sweep:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}/BCIcha/
    subdir: '.'
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: 16
  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        filename: default.log
