# optim
defaults:
  - override hydra/launcher: joblib

in_size: 15
out_size: 12
epochs: 7
optim: 'adam'
lr: 1e-3
wd: 1e-1
power: 1
seed: 3407

path: './checkpoint/mamem/'
hydra:
  run:
    dir: outputs/mamem/
  sweep:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}/mamem/
    subdir: '.'
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: 16
  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        filename: default.log

